# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meepo < Formula
  desc "Meepo help you to build your private network over Internet in easy way.
"
  homepage "https://github.com/PeerXu/meepo"
  version "0.5.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/PeerXu/meepo/releases/download/0.5.0/meepo_darwin_amd64.tar.gz"
    sha256 "ef6647f89d2be0e42bc59bd17dbe0046fc1847d2b42e720e5ef9eebd42df9e28"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/PeerXu/meepo/releases/download/0.5.0/meepo_darwin_arm64.tar.gz"
    sha256 "353fbcf05e8c860e201c1ab1beb9b819b0e0147178d9849a7930283390310020"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/PeerXu/meepo/releases/download/0.5.0/meepo_linux_amd64.tar.gz"
    sha256 "c435cc9b0771627f74dc4ce25e6ced00a3e1b7da6ae01e579b276ecb14c21560"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/PeerXu/meepo/releases/download/0.5.0/meepo_linux_armv6.tar.gz"
    sha256 "0078d66f0b7a16ff11c6595d0a26378cb0812894f021ca9ce5b99e9a4a30ea80"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/PeerXu/meepo/releases/download/0.5.0/meepo_linux_arm64.tar.gz"
    sha256 "1e314be9c7ebdb0ab55b6f011a8f3235d16fb9319e83c8754f898abd7232a03d"
  end

  def install
    bin.install "meepo"
  end

  test do
    system "#{bin}/meepo version"
  end
end
