# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meepo < Formula
  desc "Meepo help you to build your private network over Internet in easy way.
"
  homepage "https://github.com/PeerXu/meepo"
  version "0.4.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/PeerXu/meepo/releases/download/0.4.2/meepo_darwin_amd64.tar.gz"
    sha256 "b941c5386a4b205e27743ceb0863c4dd6d092d378407c1527e935cea9e838586"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/PeerXu/meepo/releases/download/0.4.2/meepo_darwin_arm64.tar.gz"
    sha256 "cef2ce41e4b8f65d16a4ac63bc1164c324d36fb67e3026cac70460815ee41236"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/PeerXu/meepo/releases/download/0.4.2/meepo_linux_amd64.tar.gz"
    sha256 "df58520b91b1fd1d93237a994307442817730b03f756862232962273fcc187fc"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/PeerXu/meepo/releases/download/0.4.2/meepo_linux_armv6.tar.gz"
    sha256 "2d72c60d0235eeaf65900474c9a22ee200ed8e8c6f25dc999be8df3f9e4e9ff5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/PeerXu/meepo/releases/download/0.4.2/meepo_linux_arm64.tar.gz"
    sha256 "6ce0f4c95a71edea0b0ff7e2b290e686c4b5dddcdbfc7b89321339f91679715f"
  end

  def install
    bin.install "meepo"
  end

  test do
    system "#{bin}/meepo version"
  end
end
