# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meepo < Formula
  desc "Meepo help you to build your private network over Internet in easy way.
"
  homepage "https://github.com/PeerXu/meepo"
  version "0.8.0-alpha.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/PeerXu/meepo/releases/download/0.8.0-alpha.3/meepo_darwin_arm64.tar.gz"
      sha256 "75c48c8a41047f5672ef804b5ea4a44161f7d07d62a5c86a7dc8174d9aa36401"

      def install
        bin.install "meepo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PeerXu/meepo/releases/download/0.8.0-alpha.3/meepo_darwin_amd64.tar.gz"
      sha256 "0f62cb6d09031b7184e9f3a927dabe8a39dfc4c6ae5faf2025ef726ef8c24f05"

      def install
        bin.install "meepo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeerXu/meepo/releases/download/0.8.0-alpha.3/meepo_linux_arm64.tar.gz"
      sha256 "5ff4f785d4f37729cb611bae2804d109dc17f6cec3ce45a878f5d3e45dab9a45"

      def install
        bin.install "meepo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PeerXu/meepo/releases/download/0.8.0-alpha.3/meepo_linux_armv6.tar.gz"
      sha256 "e64845ccd13cefce1d8d83d116a8b15b8fe211950627fd357ba2527e050a582c"

      def install
        bin.install "meepo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PeerXu/meepo/releases/download/0.8.0-alpha.3/meepo_linux_amd64.tar.gz"
      sha256 "9c07043bcf71d005b958a02c1ddc0763b1fafc0e6c8fcc4e27b1d94782ef60a3"

      def install
        bin.install "meepo"
      end
    end
  end

  test do
    system "#{bin}/meepo version"
  end
end
